substitutions:
  name: everything-presence-lite-ef3b6c
  friendly_name: Everything Presence Lite ef3b6c
packages:
  EverythingSmartTechnology.Everything Presence Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: j7y+nOVWpjZ8ilAA74Rsy78NZnc03SCbyXIaclOeyJs=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
